show databases;

create database sb012;

USE sb012;

CREATE TABLE EMPLOYEE(
	ID int NOT NULL PRIMARY KEY,
	AGE int NOT NULL,
	FIRST_NAME varchar (255),
	LAST_NAME varchar (255)
);

SELECT * FROM EMPLOYEE;
    
INSERT INTO EMPLOYEE VALUES (100,21,'Souvik','Ghosh');
INSERT INTO EMPLOYEE VALUES (101,25,'Nayan','Sahare');
INSERT INTO EMPLOYEE VALUES (102,30,'Devendra','Dhar');
INSERT INTO EMPLOYEE VALUES (103,31,'Ayaz','Ahmad');
INSERT INTO EMPLOYEE VALUES (104,37,'Athar','Zafar');


DELIMITER //

CREATE PROCEDURE GetAllEmployee()
BEGIN
	SELECT *  FROM EMPLOYEE;
END //

DELIMITER ;


CREATE TABLE BOOKS(
	BOOK_ID int NOT NULL PRIMARY KEY,
	BOOK_NAME varchar(255),
	BOOK_AUTHOR varchar(255),
	BOOK_PUBLICATION varchar(255),
	BOOK_PRICE int,
	BOOK_ISBN BIGINT
);


SELECT * FROM BOOKS;



CREATE TABLE USERS(
	USERS_NAME varchar(255),
	USERS_PASSWORD varchar(255)
);


SELECT * FROM USERS;

INSERT INTO USERS VALUES ('admin','admin@12345');
INSERT INTO USERS VALUES ('root','root@12345');

SELECT * FROM USERS where USERS_NAME = 'admin' AND USERS_PASSWORD = 'admin@12345';
SELECT * FROM USERS where USERS_NAME = 'admin' AND USERS_PASSWORD = 'admin@1234';


SELECT * FROM STUDENT_INFO;
SELECT * FROM EMPLOYEE_DETAILS;
SELECT * FROM  CUSTOMER_INFO;
SELECT * FROM EMPLOYEE_INFO where EMPLOYEE_ID=1;

-- ONE TO ONE UNI MAPPING
SELECT * FROM  ADDRESS_DETAILS;
SELECT * FROM  STUDENT_DETAILS;

SELECT * FROM AADDRESS_DETAILS;
SELECT * FROM ASTUDENT_DETAILS;

-- ONE TO ONE Bi MAPPING
SELECT * FROM ADDRESS_INFO;
SELECT * FROM STUDENT_DATA;

SELECT * FROM  ASTUDENT_DATA;
SELECT * FROM  AADDRESS_INFO;

-- One To Many Mapping
SELECT * FROM  ORDER_DATA;
SELECT * FROM  CUSTOMER_DETAILS;

SELECT * FROM  AORDER_DATA;
SELECT * FROM  ACUSTOMER_DETAILS;


SET foreign_key_checks = 0;

drop table CUSTOMER_ACCOUNT;
drop table CUSTOMER_DETAILS_BI;
drop table ACCOUNT_DATA_BI;

SET foreign_key_checks = 1;


SELECT * FROM  CUSTOMER_DETAILS_BI;
SELECT * FROM  ACCOUNT_DATA_BI;
SELECT * FROM  CUSTOMER_ACCOUNT;

SELECT * FROM  A_CUSTOMER_DETAILS_BI;
SELECT * FROM  A_ACCOUNT_DATA_BI;
SELECT * FROM  A_CUSTOMER_ACCOUNT_PK;

SELECT * FROM  EMPLOYEE_DATA;
SELECT * FROM  EMPLOYEE_COURSE;
SELECT * FROM  EMPLOYEE_EMAIL;
SELECT * FROM  EMPLOYEE_MARKS;
SELECT * FROM  EMPLOYEE_PHONE;
SELECT * FROM  EMPLOYEE_REFERANCE;


SELECT * FROM  A_EMPLOYEE_DATA;
SELECT * FROM  A_EMPLOYEE_COURSE;
SELECT * FROM  A_EMPLOYEE_EMAIL;
SELECT * FROM  A_EMPLOYEE_MARKS;
SELECT * FROM  A_EMPLOYEE_PHONE;
SELECT * FROM  A_EMPLOYEE_REFERANCE;

SELECT * FROM  LOG_STUDENT_INFO;