show databases;

create database sb012;

USE sb012;

CREATE TABLE EMPLOYEE(
	ID int NOT NULL PRIMARY KEY,
	AGE int NOT NULL,
	FIRST_NAME varchar (255),
	LAST_NAME varchar (255)
);

SELECT * FROM EMPLOYEE;
    
INSERT INTO EMPLOYEE VALUES (100,21,'Souvik','Ghosh');
INSERT INTO EMPLOYEE VALUES (101,25,'Nayan','Sahare');
INSERT INTO EMPLOYEE VALUES (102,30,'Devendra','Dhar');
INSERT INTO EMPLOYEE VALUES (103,31,'Ayaz','Ahmad');
INSERT INTO EMPLOYEE VALUES (104,37,'Athar','Zafar');


DELIMITER //

CREATE PROCEDURE GetAllEmployee()
BEGIN
	SELECT *  FROM EMPLOYEE;
END //

DELIMITER ;


CREATE TABLE BOOKS(
	BOOK_ID int NOT NULL PRIMARY KEY,
	BOOK_NAME varchar(255),
	BOOK_AUTHOR varchar(255),
	BOOK_PUBLICATION varchar(255),
	BOOK_PRICE int,
	BOOK_ISBN BIGINT
);


SELECT * FROM BOOKS;



CREATE TABLE USERS(
	USERS_NAME varchar(255),
	USERS_PASSWORD varchar(255)
);


SELECT * FROM USERS;

INSERT INTO USERS VALUES ('admin','admin@12345');
INSERT INTO USERS VALUES ('root','root@12345');

SELECT * FROM USERS where USERS_NAME = 'admin' AND USERS_PASSWORD = 'admin@12345';
SELECT * FROM USERS where USERS_NAME = 'admin' AND USERS_PASSWORD = 'admin@1234';
